from setuptools import find_packages
from setuptools import setup

setup(
    name="rainbowbatch",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "autosub3",
        "beautifulsoup4",
        "google-api-python-client",
        "google-auth",
        "google-auth-oauthlib",
        "lxml",
        "maya",
        "mwclient",
        "natsort",
        "openai-whisper",
        "pandas",
        "parse",
        "praw",
        "pygit2",
        "pypandoc",
        "python-box",
        "pytimeparse",
        "requests",
        "spacy",
        "spotipy",
        "srt",
        "three-merge",
        "tqdm",
        "twitch-python",
        "webvtt-py",
        "wikitextparser",
    ],
)
